/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConnectAgents.java
 *
 * Created on Sep 22, 2010, 4:39:00 AM
 */
package flexisim.agent;

import flexisim.views.FlexiSimView;
import flexisim.views.NewProject;
import flexisim.node.NewNode;
import flexisim.views.FlexiSimApp;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author harshit
 */
public class ConnectAgents extends javax.swing.JDialog {

    public static String agent1, agent2;

    /** Creates new form ConnectAgents */
    public ConnectAgents(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agent1Label = new javax.swing.JLabel();
        agent2Label = new javax.swing.JLabel();
        agent1ComboBox = new javax.swing.JComboBox();
        agent2ComboBox = new javax.swing.JComboBox();
        connectButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(flexisim.views.FlexiSimApp.class).getContext().getResourceMap(ConnectAgents.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        agent1Label.setText(resourceMap.getString("agent1Label.text")); // NOI18N
        agent1Label.setName("agent1Label"); // NOI18N

        agent2Label.setText(resourceMap.getString("agent2Label.text")); // NOI18N
        agent2Label.setName("agent2Label"); // NOI18N

        agent1ComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        for(int i=0;i<50;i++)
        {
            if(NewProject.obam.getAgentname(i)!=null)
            agent1ComboBox.addItem(NewProject.obam.getAgentname(i));
        }
        agent1ComboBox.setName("agent1ComboBox"); // NOI18N

        agent2ComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        for(int i=0;i<50;i++)
        {
            if(NewProject.obam.getAgentname(i)!=null)
            agent2ComboBox.addItem(NewProject.obam.getAgentname(i));
        }
        agent2ComboBox.setName("agent2ComboBox"); // NOI18N

        connectButton.setText(resourceMap.getString("connectButton.text")); // NOI18N
        connectButton.setName("connectButton"); // NOI18N
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(connectButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(agent2Label)
                        .addGap(18, 18, 18)
                        .addComponent(agent2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(agent1Label)
                        .addGap(18, 18, 18)
                        .addComponent(agent1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agent1Label)
                    .addComponent(agent1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agent2Label)
                    .addComponent(agent2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // TODO add your handling code here:
        agent1 = (String) agent1ComboBox.getSelectedItem();
        agent2 = (String) agent2ComboBox.getSelectedItem();
        if (agent1.equals(agent2)) {
            dispose();
            JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
            JOptionPane.showMessageDialog(mainFrame, "Agents should be different.", "Agents Cannot be Connected", JOptionPane.ERROR_MESSAGE);
        } else if (NewProject.obam.agentCompatibility(agent1, agent2) == 0) {
            dispose();
            JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
            JOptionPane.showMessageDialog(mainFrame, "Agents should be compatible.", "Agents Cannot be Connected", JOptionPane.ERROR_MESSAGE);
        } else {
            NewNode.obj.connectWrite(agent1, agent2);
            FlexiSimView.statusTabbedPane.setSelectedIndex(0);
            FlexiSimView.statusTextArea.append("Agents connected Successfully\n");
            NewProject.obpd.setLog("Agents connected Successfully\n");
            FlexiSimView.codeTextAreaWrite();
            dispose();

        }
    }//GEN-LAST:event_connectButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ConnectAgents dialog = new ConnectAgents(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox agent1ComboBox;
    private javax.swing.JLabel agent1Label;
    private javax.swing.JComboBox agent2ComboBox;
    private javax.swing.JLabel agent2Label;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton connectButton;
    // End of variables declaration//GEN-END:variables
}
