/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewAgent.java
 *
 * Created on Sep 19, 2010, 2:11:59 AM
 */
package flexisim.agent;

import javax.swing.JFrame;
import flexisim.views.FlexiSimApp;
import flexisim.views.FlexiSimView;
import flexisim.views.NewProject;
import flexisim.application.NewApplication;
import flexisim.node.NewNode;
import javax.swing.JOptionPane;

/**
 *
 * @author harshit
 */
public class NewAgent extends javax.swing.JDialog {

    public static String aname, atype, anode;
    public static long apsize = 0;
    boolean flag = true;

    /** Creates new form NewAgent */
    public NewAgent(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sourceLabel = new javax.swing.JLabel();
        sourceNameLabel = new javax.swing.JLabel();
        agentNameTextField = new javax.swing.JTextField();
        sourceTypeComboBox = new javax.swing.JComboBox();
        sourceNodeComboBox = new javax.swing.JComboBox();
        OkAgentButton = new javax.swing.JButton();
        typeLabel = new javax.swing.JLabel();
        nodeLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(flexisim.views.FlexiSimApp.class).getContext().getResourceMap(NewAgent.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        sourceLabel.setText(resourceMap.getString("sourceLabel.text")); // NOI18N
        sourceLabel.setName("sourceLabel"); // NOI18N

        sourceNameLabel.setText(resourceMap.getString("sourceNameLabel.text")); // NOI18N
        sourceNameLabel.setName("sourceNameLabel"); // NOI18N

        agentNameTextField.setText(resourceMap.getString("agentNameTextField.text")); // NOI18N
        agentNameTextField.setName("agentNameTextField"); // NOI18N

        sourceTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TCP", "UDP", "Null", "TCPSink" }));
        sourceTypeComboBox.setName("sourceTypeComboBox"); // NOI18N

        sourceNodeComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        for(int i=0;i<50;i++)
        {
            if(NewProject.obnm.getNodename(i)!=null)
            sourceNodeComboBox.addItem(NewProject.obnm.getNodename(i));
        }
        sourceNodeComboBox.setName("sourceNodeComboBox"); // NOI18N

        OkAgentButton.setText(resourceMap.getString("OkAgentButton.text")); // NOI18N
        OkAgentButton.setName("OkAgentButton"); // NOI18N
        getRootPane().setDefaultButton (OkAgentButton);
        OkAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkAgentButtonActionPerformed(evt);
            }
        });

        typeLabel.setText(resourceMap.getString("typeLabel.text")); // NOI18N
        typeLabel.setName("typeLabel"); // NOI18N

        nodeLabel.setText(resourceMap.getString("nodeLabel.text")); // NOI18N
        nodeLabel.setName("nodeLabel"); // NOI18N

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLabel)
                            .addComponent(sourceNameLabel)
                            .addComponent(nodeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourceTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sourceNodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sourceLabel))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OkAgentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sourceLabel)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceNameLabel)
                    .addComponent(agentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(sourceTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodeLabel)
                    .addComponent(sourceNodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OkAgentButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-260)/2, (screenSize.height-251)/2, 260, 251);
    }// </editor-fold>//GEN-END:initComponents

    private void OkAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkAgentButtonActionPerformed
        // TODO add your handling code here:
        atype = (String) sourceTypeComboBox.getSelectedItem();
        anode = (String) sourceNodeComboBox.getSelectedItem();
        try {
            aname = (String) agentNameTextField.getText();
        } catch (Exception e) {
            dispose();
            JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
            JOptionPane.showMessageDialog(mainFrame, "Agent name must be specified.", "Agent Cannot be Created", JOptionPane.ERROR_MESSAGE);
            flag = false;
        }
        if (flag == true) {
            if (NewProject.obam.agentNameCheck(aname) == 0) {
                dispose();
                JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
                JOptionPane.showMessageDialog(mainFrame, "Agent name must be unique.", "Agent Cannot be Created", JOptionPane.ERROR_MESSAGE);
            } else if (!atype.equals("Null") && !atype.equals("TCPSink")) {
                JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
                NewApplication newapplication = new NewApplication(mainFrame);
                newapplication.setLocationRelativeTo(mainFrame);
                FlexiSimApp.getApplication().show(newapplication);
                dispose();
            } else {
                FlexiSimView.statusTabbedPane.setSelectedIndex(0);
                FlexiSimView.statusTextArea.append("New Agent " + atype + " on " + anode + " has been created successfully\n");
                NewProject.obpd.setLog("New Agent " + atype + " on " + anode + " has been created successfully\n");
                NewProject.obam.addAgent(aname, atype, anode);
                NewNode.obj.agentWrite(aname, atype, anode);
                FlexiSimView.codeTextAreaWrite();
                dispose();
            }
        }
    }//GEN-LAST:event_OkAgentButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NewAgent dialog = new NewAgent(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkAgentButton;
    public static javax.swing.JTextField agentNameTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel nodeLabel;
    private javax.swing.JLabel sourceLabel;
    private javax.swing.JLabel sourceNameLabel;
    private javax.swing.JComboBox sourceNodeComboBox;
    private javax.swing.JComboBox sourceTypeComboBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
