/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewEvent.java
 *
 * Created on Sep 24, 2010, 4:24:53 AM
 */
package flexisim.event;

import flexisim.node.NewNode;
import flexisim.views.FlexiSimApp;
import java.text.DecimalFormat;
import flexisim.views.FlexiSimView;
import flexisim.views.NewProject;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author harshit
 */
public class NewEvent extends javax.swing.JDialog {

    public String node1, node2, agentSelected, agentnode, link, agent;
    public String linkSelected = new String();
    public int indexLink = 0, indexAgent = 0;
    int y = 0, eri = 0;

    /** Creates new form NewEvent */
    public NewEvent(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventTabbedPane = new javax.swing.JTabbedPane();
        linkPanel = new javax.swing.JPanel();
        linkLabel = new javax.swing.JLabel();
        eventLinkComboBox = new javax.swing.JComboBox();
        downLinkFormattedTextField = new javax.swing.JFormattedTextField(new DecimalFormat("#.00"));
        jLabel2 = new javax.swing.JLabel();
        upLinkFormattedTextField = new javax.swing.JFormattedTextField(new DecimalFormat("#.00"));
        jLabel3 = new javax.swing.JLabel();
        downLinkLabel = new javax.swing.JLabel();
        upLinkLabel = new javax.swing.JLabel();
        agentPanel = new javax.swing.JPanel();
        agentNameLabel = new javax.swing.JLabel();
        agentEventComboBox = new javax.swing.JComboBox();
        deAgentFormattedTextField = new javax.swing.JFormattedTextField(new DecimalFormat("#.00"));
        deattachAgentLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        eventOkButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(flexisim.views.FlexiSimApp.class).getContext().getResourceMap(NewEvent.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        eventTabbedPane.setName("eventTabbedPane"); // NOI18N

        linkPanel.setName("linkPanel"); // NOI18N

        linkLabel.setText(resourceMap.getString("linkLabel.text")); // NOI18N
        linkLabel.setName("linkLabel"); // NOI18N

        eventLinkComboBox.setModel(new javax.swing.DefaultComboBoxModel(NewProject.oblm.showLink()));
        eventLinkComboBox.setName("eventLinkComboBox"); // NOI18N
        eventLinkComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                eventLinkComboBoxItemStateChanged(evt);
            }
        });
        linkSelected=(String)eventLinkComboBox.getSelectedItem();

        downLinkFormattedTextField.setText(resourceMap.getString("downLinkFormattedTextField.text")); // NOI18N
        downLinkFormattedTextField.setName("downLinkFormattedTextField"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        upLinkFormattedTextField.setText(resourceMap.getString("upLinkFormattedTextField.text")); // NOI18N
        upLinkFormattedTextField.setName("upLinkFormattedTextField"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        downLinkLabel.setText(resourceMap.getString("downLinkLabel.text")); // NOI18N
        downLinkLabel.setName("downLinkLabel"); // NOI18N

        upLinkLabel.setText(resourceMap.getString("upLinkLabel.text")); // NOI18N
        upLinkLabel.setName("upLinkLabel"); // NOI18N

        javax.swing.GroupLayout linkPanelLayout = new javax.swing.GroupLayout(linkPanel);
        linkPanel.setLayout(linkPanelLayout);
        linkPanelLayout.setHorizontalGroup(
            linkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(linkPanelLayout.createSequentialGroup()
                        .addComponent(linkLabel)
                        .addGap(18, 18, 18)
                        .addComponent(eventLinkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(linkPanelLayout.createSequentialGroup()
                        .addGroup(linkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(downLinkLabel)
                            .addComponent(upLinkLabel))
                        .addGap(12, 12, 12)
                        .addGroup(linkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(downLinkFormattedTextField)
                            .addComponent(upLinkFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(linkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        linkPanelLayout.setVerticalGroup(
            linkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(linkPanelLayout.createSequentialGroup()
                        .addGroup(linkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(linkLabel)
                            .addComponent(eventLinkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(linkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(downLinkLabel)
                            .addComponent(downLinkFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(linkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upLinkLabel)
                    .addComponent(upLinkFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        downLinkFormattedTextField.setValue(0.00);
        for (int j = NewProject.obed.getI(); j >= 0; j--) {
            if (NewProject.obed.getLinkEntered(j).equals((String)eventLinkComboBox.getSelectedItem())){
                downLinkFormattedTextField.setValue(NewProject.obed.getDownValue(j));
                break;
            }
        }
        upLinkFormattedTextField.setValue(0.00);
        for (int j = NewProject.obed.getI(); j >= 0; j--) {
            if (NewProject.obed.getLinkEntered(j).equals((String)eventLinkComboBox.getSelectedItem())){
                upLinkFormattedTextField.setValue(NewProject.obed.getUpValue(j));
                break;
            }
        }

        eventTabbedPane.addTab(resourceMap.getString("linkPanel.TabConstraints.tabTitle"), linkPanel); // NOI18N

        agentPanel.setName("agentPanel"); // NOI18N

        agentNameLabel.setText(resourceMap.getString("agentNameLabel.text")); // NOI18N
        agentNameLabel.setName("agentNameLabel"); // NOI18N

        agentEventComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        for(int i=0;i<50;i++)
        {
            if(NewProject.obam.getAgentname(i)!=null)
            agentEventComboBox.addItem(NewProject.obam.getAgentname(i));
        }
        agentEventComboBox.setName("agentEventComboBox"); // NOI18N
        agentEventComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                agentEventComboBoxItemStateChanged(evt);
            }
        });
        agentSelected=(String)agentEventComboBox.getSelectedItem();

        deAgentFormattedTextField.setText(resourceMap.getString("deAgentFormattedTextField.text")); // NOI18N
        deAgentFormattedTextField.setName("deAgentFormattedTextField"); // NOI18N

        deattachAgentLabel.setText(resourceMap.getString("deattachAgentLabel.text")); // NOI18N
        deattachAgentLabel.setName("deattachAgentLabel"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        javax.swing.GroupLayout agentPanelLayout = new javax.swing.GroupLayout(agentPanel);
        agentPanel.setLayout(agentPanelLayout);
        agentPanelLayout.setHorizontalGroup(
            agentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agentPanelLayout.createSequentialGroup()
                        .addComponent(deattachAgentLabel)
                        .addGap(18, 18, 18)
                        .addComponent(deAgentFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addGroup(agentPanelLayout.createSequentialGroup()
                        .addComponent(agentNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(agentEventComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        agentPanelLayout.setVerticalGroup(
            agentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agentPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(agentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agentNameLabel)
                    .addComponent(agentEventComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(agentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deattachAgentLabel)
                    .addComponent(deAgentFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        eventTabbedPane.addTab(resourceMap.getString("agentPanel.TabConstraints.tabTitle"), agentPanel); // NOI18N

        eventOkButton.setText(resourceMap.getString("eventOkButton.text")); // NOI18N
        eventOkButton.setName("eventOkButton"); // NOI18N
        getRootPane().setDefaultButton(eventOkButton);
        eventOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventOkButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eventTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eventOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(eventTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventOkButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventOkButtonActionPerformed
        // TODO add your handling code here:
        Number temp;
        NewNode.obj.clearEventWrite();

        try {
            boolean flag = true;
            for (int j = NewProject.obed.getI(); j >= 0; j--) {
                if (NewProject.obed.getLinkEntered(j).equals(linkSelected)) {
                    flag = false;
                }
            }
            if (flag) {
                temp = (Number) downLinkFormattedTextField.getValue();
                if (temp.doubleValue() > 0) {
                    NewProject.obed.increamentI();
                    NewProject.obed.setDownValue((Number) downLinkFormattedTextField.getValue(), NewProject.obed.getI());
                    NewProject.obed.setLinkEntered((String) eventLinkComboBox.getSelectedItem(), NewProject.obed.getI());
                    NewProject.obed.setUpValue(0, NewProject.obed.getI());
                }
                temp = (Number) upLinkFormattedTextField.getValue();
                if (temp.doubleValue() > 0) {
                    NewProject.obed.setUpValue(temp, NewProject.obed.getI());
                }
            }
            if (flag == false) {
                temp = (Number) downLinkFormattedTextField.getValue();
                if (temp.doubleValue() > 0.00) {
                    NewProject.obed.setDownValue(temp, indexLink);
                    NewProject.obed.setUpValue(0, indexLink);
                }
                temp = (Number) upLinkFormattedTextField.getValue();
                if (temp.doubleValue() > 0.00) {
                    NewProject.obed.setUpValue(temp, indexLink);
                }
            }
        } catch (NullPointerException ne) {
            temp = 0;
        }
        for (int l = NewProject.obed.getI(); l >= 0; l--) {
            for (int m = NewProject.obnm.nodeNum() - 1; m >= 0; m--) {
                if (NewProject.obed.getLinkEntered(l).equals(NewProject.oblm.getLink(m))) {
                    node1 = NewProject.oblm.getNode1(m);
                    node2 = NewProject.oblm.getNode2(m);
                }
            }
            if (NewProject.obed.getUpValue(l).equals(0) || NewProject.obed.getUpValue(l).doubleValue() > NewProject.obed.getDownValue(l).doubleValue()) {
                NewNode.obj.linkEventWrite(node1, node2, NewProject.obed.getUpValue(l).doubleValue(), NewProject.obed.getDownValue(l).doubleValue());
                if (NewProject.obed.getUpValue(l).doubleValue() > 0) {
                    link = "link " + node1 + " - " + node2 + " down at " + NewProject.obed.getDownValue(l).doubleValue() + " up at " + NewProject.obed.getUpValue(l).doubleValue() + "\n";
                } else {
                    link = "link " + node1 + " - " + node2 + " down at " + NewProject.obed.getDownValue(l).doubleValue() + "\n";
                }
                NewProject.obed.setEvent(link);
                FlexiSimView.statusTextArea.append("route " + node1 + "-" + node2 + " down is sheduled at " + NewProject.obed.getDownValue(l) + "s\n");
                NewProject.obpd.setLog("route " + node1 + "-" + node2 + " down is sheduled at " + NewProject.obed.getDownValue(l) + "s\n");
                if (!NewProject.obed.getUpValue(l).equals(0)) {
                    FlexiSimView.statusTextArea.append("route " + node1 + "-" + node2 + " up is sheduled at " + NewProject.obed.getUpValue(l) + "s\n");
                    NewProject.obpd.setLog("route " + node1 + "-" + node2 + " up is sheduled at " + NewProject.obed.getUpValue(l) + "s\n");
                }
            } else {
                dispose();
                JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
                JOptionPane.showMessageDialog(mainFrame, "Link Down time should be less than up time.", "Events Cannot be Scheduled", JOptionPane.ERROR_MESSAGE);
            }
        }
        try {
            boolean flag = true;
            for (int j = NewProject.obed.getK(); j >= 0; j--) {
                if (NewProject.obed.getAgentEntered(j).equals(agentSelected)) {
                    flag = false;
                }
            }
            if (flag) {
                temp = (Number) deAgentFormattedTextField.getValue();
                if (temp.doubleValue() > 0) {
                    NewProject.obed.increamentK();
                    NewProject.obed.setDeattach((Number) deAgentFormattedTextField.getValue(), NewProject.obed.getK());
                    NewProject.obed.setAgentEntered(agentSelected, NewProject.obed.getK());
                }
            }
            if (flag == false) {
                temp = (Number) deAgentFormattedTextField.getValue();
                if (temp.doubleValue() > 0) {
                    NewProject.obed.getDeattach(indexAgent);
                }
            }
        } catch (NullPointerException ne) {
            temp = 0;
        }

        for (int n = NewProject.obed.getK(); n >= 0; n--) {
            for (int p = NewProject.obam.getAgentNum() - 1; p >= 0; p--) {
                if (NewProject.obed.getAgentEntered(n).equals(NewProject.obam.getAgentname(p))) {
                    agentnode = NewProject.obam.getAgentnode(p);
                }
            }
            NewNode.obj.agentEventWrite(NewProject.obed.getAgentEntered(n), agentnode, NewProject.obed.getDeattach(n).doubleValue());
            agent = "Detach-agent at " + NewProject.obed.getDeattach(n).doubleValue() + " from " + agentnode + " the agent " + NewProject.obed.getAgentEntered(n) + "\n";
             NewProject.obed.setEvent(agent);
            FlexiSimView.statusTabbedPane.setSelectedIndex(0);
            FlexiSimView.statusTextArea.append("Agent " + NewProject.obed.getAgentEntered(n) + " deattachment is sheduled at " + NewProject.obed.getDeattach(n) + "s\n");
            NewProject.obpd.setLog("Agent " + NewProject.obed.getAgentEntered(n) + " deattachment is sheduled at " + NewProject.obed.getDeattach(n) + "s\n");
        }
        FlexiSimView.codeTextAreaWrite();
        dispose();
    }//GEN-LAST:event_eventOkButtonActionPerformed

    private void eventLinkComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_eventLinkComboBoxItemStateChanged
        // TODO add your handling code here:
        boolean flag = true;
        Number temp;
        try {
            for (int j = NewProject.obed.getI(); j >= 0; j--) {
                if (NewProject.obed.getLinkEntered(j).equals(linkSelected)) {
                    flag = false;
                }
            }
            if (flag == true) {
                temp = (Number) downLinkFormattedTextField.getValue();
                if (temp.doubleValue() > 0.00) {
                    NewProject.obed.increamentI();
                    NewProject.obed.setDownValue(temp, NewProject.obed.getI());
                    NewProject.obed.setLinkEntered(linkSelected, NewProject.obed.getI());
                    NewProject.obed.setIndex(indexLink, NewProject.obed.getI());
                    NewProject.obed.setUpValue(0, NewProject.obed.getI());
                }
                temp = (Number) upLinkFormattedTextField.getValue();
                if (temp.doubleValue() > 0.00) {
                    NewProject.obed.setUpValue(temp, NewProject.obed.getI());
                }
            }
        } catch (NullPointerException ne) {
            temp = 0;
        }
        downLinkFormattedTextField.setValue(0.00);
        upLinkFormattedTextField.setValue(0.00);
        linkSelected = (String) eventLinkComboBox.getSelectedItem();
        indexLink = eventLinkComboBox.getSelectedIndex();
        for (int j = NewProject.obed.getI(); j >= 0; j--) {
            if (NewProject.obed.getLinkEntered(j).equals(linkSelected)) {
                downLinkFormattedTextField.setValue(NewProject.obed.getDownValue(j));
                upLinkFormattedTextField.setValue(NewProject.obed.getUpValue(j));
            }
        }
        try {
            if (flag == false) {
                temp = (Number) downLinkFormattedTextField.getValue();
                if (temp.doubleValue() > 0.00) {
                    NewProject.obed.setDownValue(temp, indexLink);
                    NewProject.obed.setUpValue(0, indexLink);
                }
                temp = (Number) upLinkFormattedTextField.getValue();
                if (temp.doubleValue() > 0.00) {
                    NewProject.obed.setDownValue(temp, indexLink);
                }
            }
        } catch (NullPointerException ne) {
            temp = 0;
        }
        eventLinkComboBox.hidePopup();
        flag = true;
    }//GEN-LAST:event_eventLinkComboBoxItemStateChanged

    private void agentEventComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_agentEventComboBoxItemStateChanged
        // TODO add your handling code here:
        boolean flag = true;
        Number temp;
        for (int j = NewProject.obed.getK(); j >= 0; j--) {
            if (NewProject.obed.getAgentEntered(j).equals(agentSelected)) {
                flag = false;
            }
        }
        if (flag == true) {
            try {
                temp = (Number) deAgentFormattedTextField.getValue();
                if (temp.doubleValue() > 0) {
                    NewProject.obed.increamentK();
                    NewProject.obed.setDeattach((Number) deAgentFormattedTextField.getValue(), NewProject.obed.getK());
                    NewProject.obed.setAgentEntered(agentSelected, NewProject.obed.getK());
                }
            } catch (NullPointerException ne) {
                temp = 0;
            }
        }
        deAgentFormattedTextField.setValue(0);
        agentSelected = (String) agentEventComboBox.getSelectedItem();
        indexAgent = agentEventComboBox.getSelectedIndex();
        for (int j = NewProject.obed.getK(); j >= 0; j--) {
            if (NewProject.obed.getAgentEntered(j).equals(agentSelected)) {
                deAgentFormattedTextField.setValue(NewProject.obed.getDeattach(j));
            }
        }
        if (flag == false) {
            try {
                temp = (Number) deAgentFormattedTextField.getValue();
                if (temp.doubleValue() > 0) {
                    NewProject.obed.setDeattach((Number) deAgentFormattedTextField.getValue(), indexAgent);
                }
            } catch (NullPointerException ne) {
                temp = 0;
            }
        }
        agentEventComboBox.hidePopup();
    }//GEN-LAST:event_agentEventComboBoxItemStateChanged

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NewEvent dialog = new NewEvent(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox agentEventComboBox;
    private javax.swing.JLabel agentNameLabel;
    private javax.swing.JPanel agentPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JFormattedTextField deAgentFormattedTextField;
    private javax.swing.JLabel deattachAgentLabel;
    private javax.swing.JFormattedTextField downLinkFormattedTextField;
    private javax.swing.JLabel downLinkLabel;
    private javax.swing.JComboBox eventLinkComboBox;
    private javax.swing.JButton eventOkButton;
    private javax.swing.JTabbedPane eventTabbedPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel linkLabel;
    private javax.swing.JPanel linkPanel;
    private javax.swing.JFormattedTextField upLinkFormattedTextField;
    private javax.swing.JLabel upLinkLabel;
    // End of variables declaration//GEN-END:variables
}
