/*
 * NewApplication.java
 *
 * Created on Sep 22, 2010, 4:20:47 AM
 */
package flexisim.application;

import flexisim.node.NewNode;
import flexisim.agent.NewAgent;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import flexisim.views.FlexiSimApp;
import flexisim.views.FlexiSimView;
import flexisim.views.NewProject;
import javax.swing.JOptionPane;

/**
 *
 * @author harshit
 */
public class NewApplication extends javax.swing.JDialog {

    public static String appname, apptype, agent;
    public static double start, stop;
    boolean flag = true;

    /** Creates new form NewApplication */
    public NewApplication(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        appNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        appNameLabel = new javax.swing.JLabel();
        appTypeComboBox = new javax.swing.JComboBox();
        appTypeLabel = new javax.swing.JLabel();
        schedulingEventsLabel = new javax.swing.JLabel();
        startAppLabel = new javax.swing.JLabel();
        stopAppLabel = new javax.swing.JLabel();
        startAppFormattedTextField = new javax.swing.JFormattedTextField(new DecimalFormat("#.00"));
        stopAppFormattedTextField = new javax.swing.JFormattedTextField(new DecimalFormat("#.00"));
        okAppButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(flexisim.views.FlexiSimApp.class).getContext().getResourceMap(NewApplication.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        appLabel.setText(resourceMap.getString("appLabel.text")); // NOI18N
        appLabel.setName("appLabel"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        appNameTextField.setName("appNameTextField"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        appNameLabel.setText(resourceMap.getString("appNameLabel.text")); // NOI18N
        appNameLabel.setName("appNameLabel"); // NOI18N

        appTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FTP", "CBR","TELNET"}));
        appTypeComboBox.setName("appTypeComboBox"); // NOI18N

        appTypeLabel.setText(resourceMap.getString("appTypeLabel.text")); // NOI18N
        appTypeLabel.setName("appTypeLabel"); // NOI18N

        schedulingEventsLabel.setText(resourceMap.getString("schedulingEventsLabel.text")); // NOI18N
        schedulingEventsLabel.setName("schedulingEventsLabel"); // NOI18N

        startAppLabel.setText(resourceMap.getString("startAppLabel.text")); // NOI18N
        startAppLabel.setName("startAppLabel"); // NOI18N

        stopAppLabel.setText(resourceMap.getString("stopAppLabel.text")); // NOI18N
        stopAppLabel.setName("stopAppLabel"); // NOI18N

        startAppFormattedTextField.setName("startAppFormattedTextField"); // NOI18N

        stopAppFormattedTextField.setName("stopAppFormattedTextField"); // NOI18N

        okAppButton.setText(resourceMap.getString("okAppButton.text")); // NOI18N
        okAppButton.setName("okAppButton"); // NOI18N
        getRootPane().setDefaultButton (okAppButton);
        okAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okAppButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(appLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(appTypeLabel)
                                        .addComponent(appNameLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(appNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(appTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addContainerGap(148, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(schedulingEventsLabel)
                            .addContainerGap(132, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(stopAppLabel)
                                .addComponent(startAppLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(startAppFormattedTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                .addComponent(stopAppFormattedTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okAppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appNameLabel)
                    .addComponent(appNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appTypeLabel))
                .addGap(29, 29, 29)
                .addComponent(schedulingEventsLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startAppLabel)
                    .addComponent(startAppFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopAppLabel)
                    .addComponent(stopAppFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okAppButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-267)/2, (screenSize.height-334)/2, 267, 334);
    }// </editor-fold>//GEN-END:initComponents

    private void okAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okAppButtonActionPerformed
        // TODO add your handling code here:
        try {
            appname = (String) appNameTextField.getText();
        } catch (NullPointerException ne) {
            dispose();
            JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
            JOptionPane.showMessageDialog(mainFrame, "Application name must be specified.", "Agent Cannot be Created", JOptionPane.ERROR_MESSAGE);
            flag = false;

        }
        apptype = (String) appTypeComboBox.getSelectedItem();
        try {
            Number number = (Number) (startAppFormattedTextField.getValue());
            start = number.doubleValue();

        } catch (NullPointerException ne) {
            flag = false;
            dispose();
            JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
            JOptionPane.showMessageDialog(mainFrame, "Start time of the application must be specified.", "Agent Cannot be Created", JOptionPane.ERROR_MESSAGE);
        }
        agent = NewAgent.agentNameTextField.getText();
        try {
            Number number = (Number) stopAppFormattedTextField.getValue();
            stop = number.doubleValue();
        } catch (Exception ie) {
            stop = 0;
        }
        if (flag) {
            if ((NewAgent.atype.equals("TCP") && apptype.equals("CBR")) || (NewAgent.atype.equals("UDP") && apptype.equals("FTP"))) {
                dispose();
                JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
                JOptionPane.showMessageDialog(mainFrame, "Agents and their corresponding applications must be compatibe.", "Agent Cannot be Connected", JOptionPane.ERROR_MESSAGE);
            } else if (apptype.equals("CBR")) {
                JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
                NewCBRTraffic newcbrtraffic = new NewCBRTraffic(mainFrame);
                newcbrtraffic.setLocationRelativeTo(mainFrame);
                FlexiSimApp.getApplication().show(newcbrtraffic);
                dispose();
            } else {
                NewProject.obam.addAgent(NewAgent.aname, NewAgent.atype, NewAgent.anode);
                NewNode.obj.agentWrite(NewAgent.aname, NewAgent.atype, NewAgent.anode);
                NewNode.obj.appWrite(appname, apptype, agent, 0, 0, false, -1, -1);
                NewNode.obj.eventWrite(start, stop, appname);
                NewProject.obappm.addApp(appname, apptype);
                FlexiSimView.statusTabbedPane.setSelectedIndex(0);
                FlexiSimView.statusTextArea.append("New Agent " + NewAgent.atype + " on " + NewAgent.anode + " has been created successfully\n");
                NewProject.obpd.setLog("New Agent " + NewAgent.atype + " on " + NewAgent.anode + " has been created successfully\n");
                FlexiSimView.codeTextAreaWrite();
                dispose();
            }
        }
    }//GEN-LAST:event_okAppButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NewApplication dialog = new NewApplication(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appLabel;
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JTextField appNameTextField;
    private javax.swing.JComboBox appTypeComboBox;
    private javax.swing.JLabel appTypeLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton okAppButton;
    private javax.swing.JLabel schedulingEventsLabel;
    private javax.swing.JFormattedTextField startAppFormattedTextField;
    private javax.swing.JLabel startAppLabel;
    private javax.swing.JFormattedTextField stopAppFormattedTextField;
    private javax.swing.JLabel stopAppLabel;
    // End of variables declaration//GEN-END:variables
}
