/*
 * NewCBRTraffic.java
 *
 * Created on Sep 20, 2010, 5:43:41 AM
 */
package flexisim.application;

import flexisim.node.NewNode;
import flexisim.agent.NewAgent;
import flexisim.views.FlexiSimApp;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import flexisim.views.FlexiSimView;
import flexisim.views.NewProject;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author harshit
 */
public class NewCBRTraffic extends javax.swing.JDialog {

    /** Creates new form NewCBRTraffic */
    public static String v;
    public String tnoise;
    public static long tpktsize, maxPack;
    public static Number traffic, noiseValue;
    private boolean trafficRate = true;

    public NewCBRTraffic(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noiseButtonGroup = new javax.swing.ButtonGroup();
        trafficButtonGroup = new javax.swing.ButtonGroup();
        packetSizeLabel = new javax.swing.JLabel();
        packetSizeFormattedTextField = new javax.swing.JFormattedTextField(NumberFormat.getIntegerInstance());
        trafficRateLabel = new javax.swing.JLabel();
        trafficRateFormattedTextField = new javax.swing.JFormattedTextField(new DecimalFormat("#.000000"));
        jLabel3 = new javax.swing.JLabel();
        noiseOnRadioButton = new javax.swing.JRadioButton("On");
        noiseOffRadioButton = new javax.swing.JRadioButton("Off");
        noiseValueLabel = new javax.swing.JLabel();
        oKTrafficButton = new javax.swing.JButton();
        noiseValueTextField = new javax.swing.JFormattedTextField(NumberFormat.getIntegerInstance());
        cancelButton = new javax.swing.JButton();
        rateRadioButton = new javax.swing.JRadioButton();
        intervalRadioButton = new javax.swing.JRadioButton();
        maxPacketsLabel = new javax.swing.JLabel();
        maxPacketsFormattedTextField = new javax.swing.JFormattedTextField(NumberFormat.getIntegerInstance());
        unitLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(flexisim.views.FlexiSimApp.class).getContext().getResourceMap(NewCBRTraffic.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        packetSizeLabel.setText(resourceMap.getString("packetSizeLabel.text")); // NOI18N
        packetSizeLabel.setName("packetSizeLabel"); // NOI18N

        packetSizeFormattedTextField.setText(resourceMap.getString("packetSizeFormattedTextField.text")); // NOI18N
        packetSizeFormattedTextField.setName("packetSizeFormattedTextField"); // NOI18N

        trafficRateLabel.setText(resourceMap.getString("trafficRateLabel.text")); // NOI18N
        trafficRateLabel.setName("trafficRateLabel"); // NOI18N

        trafficRateFormattedTextField.setText(resourceMap.getString("trafficRateFormattedTextField.text")); // NOI18N
        trafficRateFormattedTextField.setName("trafficRateFormattedTextField"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        noiseButtonGroup.add(noiseOnRadioButton);
        noiseOnRadioButton.setText(resourceMap.getString("noiseOnRadioButton.text")); // NOI18N
        noiseOnRadioButton.setName("noiseOnRadioButton"); // NOI18N
        noiseOnRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noiseOnRadioButtonActionPerformed(evt);
            }
        });

        noiseButtonGroup.add(noiseOffRadioButton);
        noiseOffRadioButton.setText(resourceMap.getString("noiseOffRadioButton.text")); // NOI18N
        noiseOffRadioButton.setName("noiseOffRadioButton"); // NOI18N
        noiseOffRadioButton.setSelected(true);
        noiseOffRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noiseOffRadioButtonActionPerformed(evt);
            }
        });

        noiseValueLabel.setText(resourceMap.getString("noiseValueLabel.text")); // NOI18N
        noiseValueLabel.setName("noiseValueLabel"); // NOI18N

        oKTrafficButton.setText(resourceMap.getString("oKTrafficButton.text")); // NOI18N
        oKTrafficButton.setName("oKTrafficButton"); // NOI18N
        getRootPane().setDefaultButton (oKTrafficButton);
        oKTrafficButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oKTrafficButtonActionPerformed(evt);
            }
        });

        noiseValueTextField.setText(resourceMap.getString("noiseValueTextField.text")); // NOI18N
        noiseValueTextField.setName("noiseValueTextField"); // NOI18N
        noiseValueTextField.setEnabled(false);

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        trafficButtonGroup.add(rateRadioButton);
        rateRadioButton.setText(resourceMap.getString("rateRadioButton.text")); // NOI18N
        rateRadioButton.setName("rateRadioButton"); // NOI18N
        rateRadioButton.setSelected(true);
        rateRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateRadioButtonActionPerformed(evt);
            }
        });

        trafficButtonGroup.add(intervalRadioButton);
        intervalRadioButton.setText(resourceMap.getString("intervalRadioButton.text")); // NOI18N
        intervalRadioButton.setName("intervalRadioButton"); // NOI18N
        intervalRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intervalRadioButtonActionPerformed(evt);
            }
        });

        maxPacketsLabel.setText(resourceMap.getString("maxPacketsLabel.text")); // NOI18N
        maxPacketsLabel.setName("maxPacketsLabel"); // NOI18N

        maxPacketsFormattedTextField.setText(resourceMap.getString("maxPacketsFormattedTextField.text")); // NOI18N
        maxPacketsFormattedTextField.setName("maxPacketsFormattedTextField"); // NOI18N

        unitLabel.setText(resourceMap.getString("unitLabel.text")); // NOI18N
        unitLabel.setName("unitLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noiseOnRadioButton)
                            .addComponent(noiseOffRadioButton)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(maxPacketsLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maxPacketsFormattedTextField))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(noiseValueLabel)
                            .addGap(18, 18, 18)
                            .addComponent(noiseValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(packetSizeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(packetSizeFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(trafficRateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rateRadioButton)
                                    .addComponent(intervalRadioButton))
                                .addGap(18, 18, 18)
                                .addComponent(trafficRateFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unitLabel)
                            .addComponent(oKTrafficButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packetSizeLabel)
                    .addComponent(packetSizeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rateRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(intervalRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trafficRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unitLabel)
                            .addComponent(trafficRateFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(noiseOnRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noiseOffRadioButton)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noiseValueLabel)
                    .addComponent(noiseValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxPacketsLabel)
                    .addComponent(maxPacketsFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oKTrafficButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oKTrafficButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oKTrafficButtonActionPerformed
        try {
            tpktsize = (Long) packetSizeFormattedTextField.getValue();
            traffic = (Number) trafficRateFormattedTextField.getValue();
            try {
                maxPack = (Long) maxPacketsFormattedTextField.getValue();
            } catch (NullPointerException ne) {
                maxPack = -1;
            }
            if (noiseValueTextField.isEnabled() == true) {
                noiseValue = (Number) noiseValueTextField.getValue();
                NewNode.obj.agentWrite(NewAgent.aname, NewAgent.atype, NewAgent.anode);
                NewNode.obj.appWrite(NewApplication.appname, NewApplication.apptype, NewApplication.agent, tpktsize, traffic.doubleValue(), trafficRate, noiseValue.doubleValue(), (int) maxPack);
            } else {
                NewNode.obj.agentWrite(NewAgent.aname, NewAgent.atype, NewAgent.anode);
                NewNode.obj.appWrite(NewApplication.appname, NewApplication.apptype, NewApplication.agent, tpktsize, traffic.doubleValue(), trafficRate, -1, (int) maxPack);
            }
            NewProject.obam.addAgent(NewAgent.aname, NewAgent.atype, NewAgent.anode);
            NewNode.obj.eventWrite(NewApplication.start, NewApplication.stop, NewApplication.appname);
            FlexiSimView.statusTextArea.append("New Agent " + NewAgent.atype + " on " + NewAgent.anode + "  has been created successfully\n");
            NewProject.obpd.setLog("New Agent " + NewAgent.atype + " on " + NewAgent.anode + "  has been created successfully\n");
            FlexiSimView.codeTextAreaWrite();
            dispose();
        } catch (NullPointerException ne) {
            dispose();
            JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
            JOptionPane.showMessageDialog(mainFrame, "Specify all required fields", "Agents Cannot be Created", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_oKTrafficButtonActionPerformed

    private void noiseOffRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noiseOffRadioButtonActionPerformed
        noiseValueTextField.setEnabled(false);
    }//GEN-LAST:event_noiseOffRadioButtonActionPerformed

    private void noiseOnRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noiseOnRadioButtonActionPerformed
        noiseValueTextField.setEnabled(true);
    }//GEN-LAST:event_noiseOnRadioButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void rateRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateRadioButtonActionPerformed
        trafficRate = true;
    }//GEN-LAST:event_rateRadioButtonActionPerformed

    private void intervalRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intervalRadioButtonActionPerformed
        trafficRate = false;
}//GEN-LAST:event_intervalRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NewCBRTraffic dialog = new NewCBRTraffic(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton intervalRadioButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField maxPacketsFormattedTextField;
    private javax.swing.JLabel maxPacketsLabel;
    private javax.swing.ButtonGroup noiseButtonGroup;
    private javax.swing.JRadioButton noiseOffRadioButton;
    private javax.swing.JRadioButton noiseOnRadioButton;
    private javax.swing.JLabel noiseValueLabel;
    private javax.swing.JFormattedTextField noiseValueTextField;
    private javax.swing.JButton oKTrafficButton;
    private javax.swing.JFormattedTextField packetSizeFormattedTextField;
    private javax.swing.JLabel packetSizeLabel;
    private javax.swing.JRadioButton rateRadioButton;
    private javax.swing.ButtonGroup trafficButtonGroup;
    private javax.swing.JFormattedTextField trafficRateFormattedTextField;
    private javax.swing.JLabel trafficRateLabel;
    private javax.swing.JLabel unitLabel;
    // End of variables declaration//GEN-END:variables
}
