/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewProject.java
 *
 * Created on Oct 20, 2010, 2:59:30 AM
 */
package flexisim.views;

import java.io.File;
import javax.swing.JFileChooser;
import flexisim.agent.AgentManager;
import flexisim.application.ApplicationManager;
import flexisim.event.EventData;
import flexisim.link.LinkManager;
import flexisim.node.NodeManager;
import flexisim.node.movement.NodeMovementData;
import flexisim.node.position.NodePositionData;
import flexisim.routing.protocols.NewProtocolData;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author harshit
 */
public class NewProject extends javax.swing.JDialog {

    /** Creates new form NewProject */
    private File directory;
    private int nettypesel = 0;
    public static String projectName, projectPath;
    File current = new java.io.File(".");
    public static LinkManager oblm = null;
    public static EventData obed = null;
    public static NodePositionData obnpd = null;
    public static NodeMovementData obnmd = null;
    public static NodeManager obnm = null;
    public static AgentManager obam = null;
    public static ApplicationManager obappm = null;
    public static ProjectData obpd = null;
    public static TclWriteData obtwd = null;
    public static NewProtocolData obprd = null;

    public NewProject(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projecttypebuttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        folderTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        wiredRadioButton = new javax.swing.JRadioButton();
        wirelessRadioButton = new javax.swing.JRadioButton();
        okNewProjectButton = new javax.swing.JButton();
        cancelNewProjectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(flexisim.views.FlexiSimApp.class).getContext().getResourceMap(NewProject.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        projectNameTextField.setText(resourceMap.getString("projectNameTextField.text")); // NOI18N
        projectNameTextField.setName("projectNameTextField"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        folderTextField.setText(resourceMap.getString("folderTextField.text")); // NOI18N
        folderTextField.setName("folderTextField"); // NOI18N
        //folderTextField.setText();

        browseButton.setText(resourceMap.getString("browseButton.text")); // NOI18N
        browseButton.setName("browseButton"); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        projecttypebuttonGroup.add(wiredRadioButton);
        wiredRadioButton.setText(resourceMap.getString("wiredRadioButton.text")); // NOI18N
        wiredRadioButton.setName("wiredRadioButton"); // NOI18N
        wiredRadioButton.setSelected(true);
        wiredRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wiredRadioButtonActionPerformed(evt);
            }
        });

        projecttypebuttonGroup.add(wirelessRadioButton);
        wirelessRadioButton.setText(resourceMap.getString("wirelessRadioButton.text")); // NOI18N
        wirelessRadioButton.setName("wirelessRadioButton"); // NOI18N
        wirelessRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wirelessRadioButtonActionPerformed(evt);
            }
        });

        okNewProjectButton.setText(resourceMap.getString("okNewProjectButton.text")); // NOI18N
        okNewProjectButton.setName("okNewProjectButton"); // NOI18N
        okNewProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okNewProjectButtonActionPerformed(evt);
            }
        });

        cancelNewProjectButton.setText(resourceMap.getString("cancelNewProjectButton.text")); // NOI18N
        cancelNewProjectButton.setName("cancelNewProjectButton"); // NOI18N
        cancelNewProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNewProjectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(projectNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(folderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(browseButton))
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wirelessRadioButton)
                            .addComponent(wiredRadioButton))
                        .addGap(277, 277, 277))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelNewProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okNewProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(folderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(wiredRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wirelessRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okNewProjectButton)
                    .addComponent(cancelNewProjectButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        // TODO add your handling code here:
        directoryChooser = new JFileChooser();
        //directoryChooser.setCurrentDirectory(current);
        directoryChooser.setDialogTitle("Select Project Location");
        directoryChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        directoryChooser.setAcceptAllFileFilterUsed(false);
        if (directoryChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            directory = directoryChooser.getSelectedFile();
            folderTextField.setText(directory.getPath());
        }


    }//GEN-LAST:event_browseButtonActionPerformed

    private void wiredRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wiredRadioButtonActionPerformed
        // TODO add your handling code here:
        nettypesel = 0;
    }//GEN-LAST:event_wiredRadioButtonActionPerformed

    private void wirelessRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wirelessRadioButtonActionPerformed
        // TODO add your handling code here:
        nettypesel = 1;
    }//GEN-LAST:event_wirelessRadioButtonActionPerformed

    private void okNewProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okNewProjectButtonActionPerformed
        // TODO add your handling code here:
        try {
            projectName = projectNameTextField.getText();
        } catch (NullPointerException ne) {
            FlexiSimView.statusTextArea.append("Project Name feild name is compulsory\n");
        }
        try {
            projectPath = folderTextField.getText();
        } catch (NullPointerException ne) {
            FlexiSimView.statusTextArea.append("Please Specify the Project Directory\n");
        }
        File f = new File(projectPath + "//" + projectName);
        try {
            if (f.mkdir()) {
                obpd = new ProjectData();
                FlexiSimView.statusTextArea.append("Project created successfully\n");
                obpd.setFilename(new File(f.getPath() + "//" + projectName + ".tcl"));
                obpd.setFile(new File(f.getPath() + "//" + projectName));
                FlexiSimView.file = new File(f.getPath() + "//" + projectName);
                FlexiSimView.newNodeMenuItem.setEnabled(true);
                FlexiSimView.saveMenuItem.setEnabled(true);
                FlexiSimView.modifyExistingProtocolMenuItem.setEnabled(true);
                FlexiSimView.compileMenuItem.setEnabled(false);
                FlexiSimView.tracegraphMenuItem.setEnabled(true);
                FlexiSimView.eventsMenuItem.setEnabled(false);
                FlexiSimView.newLinkMenuItem.setEnabled(false);
                FlexiSimView.newConnectionMenuItem.setEnabled(false);
                FlexiSimView.nodeMovementMenuItem.setEnabled(false);
                FlexiSimView.runMenuItem.setEnabled(false);
                FlexiSimView.newAgentMenuItem.setEnabled(false);
                FlexiSimView.makeMenuItem.setEnabled(false);
                oblm = new LinkManager();
                obam = new AgentManager();
                obed = new EventData();
                obnm = new NodeManager();
                obnmd = new NodeMovementData();
                obnpd = new NodePositionData();
                obappm = new ApplicationManager();
                obtwd = new TclWriteData();
                NewProject.obpd.setNettype(nettypesel);
                obpd.setLog("Project created successfully\n");
                FlexiSimView.codeTextArea.setText("");
                obpd.setSaved(false);
            } else {
                JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
                JOptionPane.showMessageDialog(mainFrame,"Project Folder not created.","Project not Created Error",JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
                JOptionPane.showMessageDialog(mainFrame,"ERROR:"+e,"Project not Created Error",JOptionPane.ERROR_MESSAGE);
        }
        dispose();
    }//GEN-LAST:event_okNewProjectButtonActionPerformed

    private void cancelNewProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNewProjectButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        FlexiSimView.newNodeMenuItem.setEnabled(false);
        FlexiSimView.statusTextArea.append("Project not created:Access cancelled by user.\n");
    }//GEN-LAST:event_cancelNewProjectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NewProject dialog = new NewProject(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private JFileChooser directoryChooser;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton cancelNewProjectButton;
    private javax.swing.JTextField folderTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton okNewProjectButton;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.ButtonGroup projecttypebuttonGroup;
    private javax.swing.JRadioButton wiredRadioButton;
    private javax.swing.JRadioButton wirelessRadioButton;
    // End of variables declaration//GEN-END:variables
}
