/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NodeConfig.java
 *
 * Created on Sep 23, 2010, 11:48:59 AM
 */
package flexisim.views;

import flexisim.node.NewNode;
import java.text.DecimalFormat;
import java.text.NumberFormat;

/**
 *
 * @author harshit
 */
public class NodeConfig extends javax.swing.JDialog {

    public static String addressingtype[] = {"flat", "hierarchical", "expanded"};
    public static String adhocRouting[] = {"DIFFUSION/RATE", "DIFFUSION/PROB", "DSDV", "DSR", "FLOODING", "OMNIMCAST", "AODV", "TORA", "PUMA"};
    public static String lltype[] = {"LL"};
    public static String mactype[] = {"Mac/802_11"};
    public static String proptype[] = {"Propagation/TwoRayGround"};
    public static String ifqtype[] = {"Queue/DropTail/PriQueue"};
    public static int ifqlenth = 50;
    public static String phytype[] = {"Phy/WirelessPhy"};
    public static String propInstance[] = {"Propagation/TwoRayGround", "Propogation/Shadowing"};
    public static String antType[] = {"Antenna/OmniAntenna"};
    public static String channeltype[] = {"Channel/WirelessChannel"};
    public static String topoinstance = "topo";
    public static String wiredrouting[] = {"ON", "OFF"};
    public static String mobileip[] = {"ON", "OFF"};
    public static String energymode[] = {"EnergyModel"};
    public static float initialenergy;
    public static float rxpower;
    public static float txpower;
    public static float idlepower;
    public static String agenttrace[] = {"ON", "OFF"};
    public static String routertrace[] = {"ON", "OFF"};
    public static String mactrace[] = {"ON", "OFF"};
    public static String movementtrace[] = {"ON", "OFF"};
    public static String errproc[] = {"UniformErrorProc"};
    public static String toradebug[] = {"ON", "OFF"};
    public static String addtype, adhoc, ll, mac, prop, ifqtyp, phytyp, propins, anttyp, channeltyp, topoins, wiredrout, mobip, energymod, agentt, routert, mact, movementt;
    public static long ifqlen = 50;
    public static Number initenergy = 0, rxpow = 0, txpow = 0, idlepow = 0;
    public static double initenergyd, rxpowd, txpowd, idlepowd;

    /** Creates new form NodeConfig */
    public NodeConfig(java.awt.Frame parent) {
        super(parent);
        initComponents();
        wiredrout = "OFF";
        mobip = "OFF";
        agentt = "OFF";
        routert = "OFF";
        mact = "OFF";
        movementt = "OFF";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wiredroutingbuttonGroup = new javax.swing.ButtonGroup();
        mobileipRadioButtonGroup = new javax.swing.ButtonGroup();
        agenttracebuttonGroup = new javax.swing.ButtonGroup();
        routertracebuttonGroup = new javax.swing.ButtonGroup();
        mactracebuttonGroup = new javax.swing.ButtonGroup();
        movtracebuttonGroup = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        addressingtypeLabel = new javax.swing.JLabel();
        addressingtypeComboBox = new javax.swing.JComboBox();
        lltypeLabel = new javax.swing.JLabel();
        lltypeComboBox = new javax.swing.JComboBox();
        proptypeLabel = new javax.swing.JLabel();
        proptypeComboBox = new javax.swing.JComboBox();
        antennatypeLabel = new javax.swing.JLabel();
        antennatypeComboBox = new javax.swing.JComboBox();
        adhocLabel = new javax.swing.JLabel();
        adhocComboBox = new javax.swing.JComboBox();
        mactypeLabel = new javax.swing.JLabel();
        mactypeComboBox = new javax.swing.JComboBox();
        ifqtypeLabel = new javax.swing.JLabel();
        ifqtypeComboBox = new javax.swing.JComboBox();
        ifqlengthLabel = new javax.swing.JLabel();
        ifqlengthFormattedTextField = new javax.swing.JFormattedTextField(NumberFormat.getIntegerInstance());
        phytypeLabel = new javax.swing.JLabel();
        phytypeComboBox = new javax.swing.JComboBox();
        channeltypeLabel = new javax.swing.JLabel();
        channeltypeComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        wiredroutingRadioButton = new javax.swing.JRadioButton();
        wiredroutingRadioButton1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        energymodeComboBox = new javax.swing.JComboBox();
        agenttraceLabel = new javax.swing.JLabel();
        agentRadioButton = new javax.swing.JRadioButton();
        agentRadioButton1 = new javax.swing.JRadioButton();
        mactraceLabel = new javax.swing.JLabel();
        mactraceRadioButton = new javax.swing.JRadioButton();
        mactraceRadioButton1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        routerRadioButton = new javax.swing.JRadioButton();
        routerRadioButton1 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        movtraceRadioButton = new javax.swing.JRadioButton();
        movtraceRadioButton1 = new javax.swing.JRadioButton();
        topoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        mobileipRadioButton1 = new javax.swing.JRadioButton();
        mobileipRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        initialenergyFormattedTextField = new javax.swing.JFormattedTextField(new DecimalFormat("#.00"));
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rxpowerFormattedTextField = new javax.swing.JFormattedTextField(new DecimalFormat("#.00"));
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txpowerFormattedTextField = new javax.swing.JFormattedTextField(new DecimalFormat("#.00"));
        jLabel12 = new javax.swing.JLabel();
        nodeconfigresetButton = new javax.swing.JButton();
        nodeconfigokButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        idlepowerFormattedTextField = new javax.swing.JFormattedTextField(new DecimalFormat("#.00"));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(flexisim.views.FlexiSimApp.class).getContext().getResourceMap(NodeConfig.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jLabel9.setName("jLabel9"); // NOI18N

        addressingtypeLabel.setText(resourceMap.getString("addressingtypeLabel.text")); // NOI18N
        addressingtypeLabel.setName("addressingtypeLabel"); // NOI18N

        addressingtypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(NodeConfig.addressingtype));
        addressingtypeComboBox.setName("addressingtypeComboBox"); // NOI18N

        lltypeLabel.setText(resourceMap.getString("lltypeLabel.text")); // NOI18N
        lltypeLabel.setName("lltypeLabel"); // NOI18N

        lltypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(NodeConfig.lltype));
        lltypeComboBox.setName("lltypeComboBox"); // NOI18N

        proptypeLabel.setText(resourceMap.getString("proptypeLabel.text")); // NOI18N
        proptypeLabel.setName("proptypeLabel"); // NOI18N

        proptypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(NodeConfig.proptype));
        proptypeComboBox.setName("proptypeComboBox"); // NOI18N

        antennatypeLabel.setText(resourceMap.getString("antennatypeLabel.text")); // NOI18N
        antennatypeLabel.setName("antennatypeLabel"); // NOI18N

        antennatypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(NodeConfig.antType));
        antennatypeComboBox.setName("antennatypeComboBox"); // NOI18N

        adhocLabel.setText(resourceMap.getString("adhocLabel.text")); // NOI18N
        adhocLabel.setName("adhocLabel"); // NOI18N

        adhocComboBox.setModel(new javax.swing.DefaultComboBoxModel(NodeConfig.adhocRouting));
        adhocComboBox.setName("adhocComboBox"); // NOI18N

        mactypeLabel.setText(resourceMap.getString("mactypeLabel.text")); // NOI18N
        mactypeLabel.setName("mactypeLabel"); // NOI18N

        mactypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(NodeConfig.mactype));
        mactypeComboBox.setName("mactypeComboBox"); // NOI18N

        ifqtypeLabel.setText(resourceMap.getString("ifqtypeLabel.text")); // NOI18N
        ifqtypeLabel.setName("ifqtypeLabel"); // NOI18N

        ifqtypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(NodeConfig.ifqtype));
        ifqtypeComboBox.setName("ifqtypeComboBox"); // NOI18N

        ifqlengthLabel.setText(resourceMap.getString("ifqlengthLabel.text")); // NOI18N
        ifqlengthLabel.setName("ifqlengthLabel"); // NOI18N

        ifqlengthFormattedTextField.setName("ifqlengthFormattedTextField"); // NOI18N

        phytypeLabel.setText(resourceMap.getString("phytypeLabel.text")); // NOI18N
        phytypeLabel.setName("phytypeLabel"); // NOI18N

        phytypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(NodeConfig.phytype));
        phytypeComboBox.setName("phytypeComboBox"); // NOI18N

        channeltypeLabel.setText(resourceMap.getString("channeltypeLabel.text")); // NOI18N
        channeltypeLabel.setName("channeltypeLabel"); // NOI18N

        channeltypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(NodeConfig.channeltype));
        channeltypeComboBox.setName("channeltypeComboBox"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        wiredroutingbuttonGroup.add(wiredroutingRadioButton);
        wiredroutingRadioButton.setText(resourceMap.getString("wiredroutingRadioButton.text")); // NOI18N
        wiredroutingRadioButton.setName("wiredroutingRadioButton"); // NOI18N
        wiredroutingRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wiredroutingRadioButtonActionPerformed(evt);
            }
        });

        wiredroutingbuttonGroup.add(wiredroutingRadioButton1);
        wiredroutingRadioButton1.setText(resourceMap.getString("wiredroutingRadioButton1.text")); // NOI18N
        wiredroutingRadioButton1.setName("wiredroutingRadioButton1"); // NOI18N
        wiredroutingRadioButton1.setSelected(true);
        wiredroutingRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wiredroutingRadioButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        energymodeComboBox.setModel(new javax.swing.DefaultComboBoxModel(NodeConfig.energymode));
        energymodeComboBox.setName("energymodeComboBox"); // NOI18N

        agenttraceLabel.setText(resourceMap.getString("agenttraceLabel.text")); // NOI18N
        agenttraceLabel.setName("agenttraceLabel"); // NOI18N

        agenttracebuttonGroup.add(agentRadioButton);
        agentRadioButton.setText(resourceMap.getString("agentRadioButton.text")); // NOI18N
        agentRadioButton.setName("agentRadioButton"); // NOI18N
        agentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentRadioButtonActionPerformed(evt);
            }
        });

        agenttracebuttonGroup.add(agentRadioButton1);
        agentRadioButton1.setText(resourceMap.getString("agentRadioButton1.text")); // NOI18N
        agentRadioButton1.setName("agentRadioButton1"); // NOI18N
        agentRadioButton1.setSelected(true);
        agentRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentRadioButton1ActionPerformed(evt);
            }
        });

        mactraceLabel.setText(resourceMap.getString("mactraceLabel.text")); // NOI18N
        mactraceLabel.setName("mactraceLabel"); // NOI18N

        mactracebuttonGroup.add(mactraceRadioButton);
        mactraceRadioButton.setText(resourceMap.getString("mactraceRadioButton.text")); // NOI18N
        mactraceRadioButton.setName("mactraceRadioButton"); // NOI18N
        mactraceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mactraceRadioButtonActionPerformed(evt);
            }
        });

        mactracebuttonGroup.add(mactraceRadioButton1);
        mactraceRadioButton1.setText(resourceMap.getString("mactraceRadioButton1.text")); // NOI18N
        mactraceRadioButton1.setName("mactraceRadioButton1"); // NOI18N
        mactraceRadioButton1.setSelected(true);
        mactraceRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mactraceRadioButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        routertracebuttonGroup.add(routerRadioButton);
        routerRadioButton.setText(resourceMap.getString("routerRadioButton.text")); // NOI18N
        routerRadioButton.setName("routerRadioButton"); // NOI18N
        routerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routerRadioButtonActionPerformed(evt);
            }
        });

        routertracebuttonGroup.add(routerRadioButton1);
        routerRadioButton1.setText(resourceMap.getString("routerRadioButton1.text")); // NOI18N
        routerRadioButton1.setName("routerRadioButton1"); // NOI18N
        routerRadioButton1.setSelected(true);
        routerRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routerRadioButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        movtracebuttonGroup.add(movtraceRadioButton);
        movtraceRadioButton.setText(resourceMap.getString("movtraceRadioButton.text")); // NOI18N
        movtraceRadioButton.setName("movtraceRadioButton"); // NOI18N
        movtraceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movtraceRadioButtonActionPerformed(evt);
            }
        });

        movtracebuttonGroup.add(movtraceRadioButton1);
        movtraceRadioButton1.setText(resourceMap.getString("movtraceRadioButton1.text")); // NOI18N
        movtraceRadioButton1.setName("movtraceRadioButton1"); // NOI18N
        movtraceRadioButton1.setSelected(true);
        movtraceRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movtraceRadioButton1ActionPerformed(evt);
            }
        });

        topoLabel.setText(resourceMap.getString("topoLabel.text")); // NOI18N
        topoLabel.setName("topoLabel"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        mobileipRadioButtonGroup.add(mobileipRadioButton1);
        mobileipRadioButton1.setText(resourceMap.getString("mobileipRadioButton1.text")); // NOI18N
        mobileipRadioButton1.setName("mobileipRadioButton1"); // NOI18N
        mobileipRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileipRadioButton1ActionPerformed(evt);
            }
        });

        mobileipRadioButtonGroup.add(mobileipRadioButton2);
        mobileipRadioButton2.setText(resourceMap.getString("mobileipRadioButton2.text")); // NOI18N
        mobileipRadioButton2.setName("mobileipRadioButton2"); // NOI18N
        mobileipRadioButton1.setSelected(true);
        mobileipRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileipRadioButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        initialenergyFormattedTextField.setName("initialenergyFormattedTextField"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        rxpowerFormattedTextField.setName("rxpowerFormattedTextField"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        txpowerFormattedTextField.setName("txpowerFormattedTextField"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        nodeconfigresetButton.setText(resourceMap.getString("nodeconfigresetButton.text")); // NOI18N
        nodeconfigresetButton.setName("nodeconfigresetButton"); // NOI18N
        nodeconfigresetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodeconfigresetButtonActionPerformed(evt);
            }
        });

        nodeconfigokButton.setText(resourceMap.getString("nodeconfigokButton.text")); // NOI18N
        nodeconfigokButton.setName("nodeconfigokButton"); // NOI18N
        nodeconfigokButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodeconfigokButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        idlepowerFormattedTextField.setText(resourceMap.getString("idlepowerFormattedTextField.text")); // NOI18N
        idlepowerFormattedTextField.setName("idlepowerFormattedTextField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lltypeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressingtypeLabel)
                            .addComponent(proptypeLabel)
                            .addComponent(antennatypeLabel)
                            .addComponent(adhocLabel)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(adhocComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(antennatypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(proptypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addressingtypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lltypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 84, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(agentRadioButton)
                                    .addComponent(wiredroutingRadioButton)
                                    .addComponent(routerRadioButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(routerRadioButton1)
                                    .addComponent(agentRadioButton1)
                                    .addComponent(wiredroutingRadioButton1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(agenttraceLabel)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mactypeLabel)
                    .addComponent(phytypeLabel)
                    .addComponent(ifqlengthLabel)
                    .addComponent(ifqtypeLabel)
                    .addComponent(channeltypeLabel)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11)
                        .addComponent(mactraceLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(energymodeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(channeltypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phytypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ifqtypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mactypeComboBox, 0, 81, Short.MAX_VALUE)
                        .addComponent(ifqlengthFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(movtraceRadioButton)
                            .addComponent(mactraceRadioButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movtraceRadioButton1)
                            .addComponent(mactraceRadioButton1))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addGap(389, 389, 389))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topoLabel)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nodeconfigresetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(nodeconfigokButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mobileipRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mobileipRadioButton2)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idlepowerFormattedTextField)
                            .addComponent(rxpowerFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel14))
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txpowerFormattedTextField)
                    .addComponent(initialenergyFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressingtypeLabel)
                    .addComponent(addressingtypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mactypeLabel)
                    .addComponent(mactypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lltypeLabel)
                    .addComponent(lltypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ifqtypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ifqtypeLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proptypeLabel)
                            .addComponent(proptypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(antennatypeLabel)
                            .addComponent(antennatypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phytypeLabel)
                            .addComponent(phytypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adhocLabel)
                            .addComponent(adhocComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(channeltypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(channeltypeLabel)))
                    .addComponent(ifqlengthLabel)
                    .addComponent(ifqlengthFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wiredroutingRadioButton)
                        .addComponent(wiredroutingRadioButton1)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3))
                    .addComponent(energymodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agenttraceLabel)
                    .addComponent(agentRadioButton1)
                    .addComponent(agentRadioButton)
                    .addComponent(mactraceLabel)
                    .addComponent(mactraceRadioButton)
                    .addComponent(mactraceRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(routerRadioButton)
                    .addComponent(routerRadioButton1)
                    .addComponent(jLabel11)
                    .addComponent(movtraceRadioButton1)
                    .addComponent(movtraceRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(topoLabel)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(mobileipRadioButton1)
                        .addComponent(jLabel4)
                        .addComponent(initialenergyFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(mobileipRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rxpowerFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(txpowerFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nodeconfigresetButton)
                            .addComponent(nodeconfigokButton)
                            .addComponent(cancelButton)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idlepowerFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wiredroutingRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wiredroutingRadioButtonActionPerformed
        // TODO add your handling code here:
        wiredrout = "ON";
}//GEN-LAST:event_wiredroutingRadioButtonActionPerformed

    private void wiredroutingRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wiredroutingRadioButton1ActionPerformed
        // TODO add your handling code here:
        wiredrout = "OFF";
}//GEN-LAST:event_wiredroutingRadioButton1ActionPerformed

    private void agentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentRadioButtonActionPerformed
        // TODO add your handling code here:
        agentt = "ON";
}//GEN-LAST:event_agentRadioButtonActionPerformed

    private void agentRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentRadioButton1ActionPerformed
        // TODO add your handling code here:
        agentt = "OFF";
}//GEN-LAST:event_agentRadioButton1ActionPerformed

    private void mactraceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mactraceRadioButtonActionPerformed
        // TODO add your handling code here:
        mact = "ON";
}//GEN-LAST:event_mactraceRadioButtonActionPerformed

    private void mactraceRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mactraceRadioButton1ActionPerformed
        // TODO add your handling code here:
        mact = "OFF";
}//GEN-LAST:event_mactraceRadioButton1ActionPerformed

    private void routerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routerRadioButtonActionPerformed
        // TODO add your handling code here:
        routert = "ON";
}//GEN-LAST:event_routerRadioButtonActionPerformed

    private void routerRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routerRadioButton1ActionPerformed
        // TODO add your handling code here:
        routert = "OFF";
}//GEN-LAST:event_routerRadioButton1ActionPerformed

    private void movtraceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movtraceRadioButtonActionPerformed
        // TODO add your handling code here:
        movementt = "ON";
}//GEN-LAST:event_movtraceRadioButtonActionPerformed

    private void movtraceRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movtraceRadioButton1ActionPerformed
        // TODO add your handling code here:
        movementt = "OFF";
}//GEN-LAST:event_movtraceRadioButton1ActionPerformed

    private void mobileipRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileipRadioButton1ActionPerformed
        // TODO add your handling code here:
        mobip = "ON";
}//GEN-LAST:event_mobileipRadioButton1ActionPerformed

    private void mobileipRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileipRadioButton2ActionPerformed
        // TODO add your handling code here:
        mobip = "OFF";
}//GEN-LAST:event_mobileipRadioButton2ActionPerformed

    private void nodeconfigresetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodeconfigresetButtonActionPerformed
        // TODO add your handling code here:
        movtraceRadioButton1.setSelected(true);
        routerRadioButton1.setSelected(true);
        wiredroutingRadioButton1.setSelected(true);
        mactraceRadioButton1.setSelected(true);
        agentRadioButton1.setSelected(true);
        mobileipRadioButton1.setSelected(true);
        txpowerFormattedTextField.setValue(0);
        rxpowerFormattedTextField.setValue(0);
        ifqlengthFormattedTextField.setValue(0);
        initialenergyFormattedTextField.setValue(0);
        adhocComboBox.setSelectedIndex(0);
        addressingtypeComboBox.setSelectedIndex(0);
}//GEN-LAST:event_nodeconfigresetButtonActionPerformed

    private void nodeconfigokButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodeconfigokButtonActionPerformed
        // TODO add your handling code here:
        try {
            addtype = (String) addressingtypeComboBox.getSelectedItem();
            adhoc = (String) adhocComboBox.getSelectedItem();
            ll = (String) lltypeComboBox.getSelectedItem();
            mac = (String) mactypeComboBox.getSelectedItem();
            prop = (String) proptypeComboBox.getSelectedItem();
            ifqtyp = (String) ifqtypeComboBox.getSelectedItem();
            phytyp = (String) phytypeComboBox.getSelectedItem();
            anttyp = (String) antennatypeComboBox.getSelectedItem();
            channeltyp = (String) channeltypeComboBox.getSelectedItem();
            energymod = (String) energymodeComboBox.getSelectedItem();
        } catch (NullPointerException e) {
        }
        try {
            ifqlen = (Long) ifqlengthFormattedTextField.getValue();
        } catch (NullPointerException e) {
            ifqlen = 0;
        }
        try {
            rxpow = (Number) rxpowerFormattedTextField.getValue();
            rxpowd = rxpow.doubleValue();
        } catch (NullPointerException e) {
            rxpowd = 0;
        }
        try {
            idlepow = (Number) idlepowerFormattedTextField.getValue();
            idlepowd = idlepow.doubleValue();
        } catch (NullPointerException e) {
            idlepowd = 0;
        }
        try {
            txpow = (Number) txpowerFormattedTextField.getValue();
            txpowd = txpow.doubleValue();
        } catch (NullPointerException e) {
            txpowd = 0;
        }
        try {
            initenergy = (Number) initialenergyFormattedTextField.getValue();
            initenergyd = initenergy.doubleValue();
        } catch (NullPointerException e) {
            initenergyd = 0;
        }
        NewNode.obj.clearNodeConfigWrite();
        NewNode.obj.nodeconfigwrite(addtype, adhoc, ll, mac, prop, ifqtyp, ifqlen, phytyp, anttyp, channeltyp, topoinstance, wiredrout, mobip, energymod, initenergyd, rxpowd, txpowd, idlepowd, agentt, routert, mact, movementt);
        FlexiSimView.statusTabbedPane.setSelectedIndex(0);
        FlexiSimView.statusTextArea.append("Node Configured Successfully\n");
        NewProject.obpd.setLog("Node Configured Successfully\n");
        FlexiSimView.codeTextAreaWrite();
        dispose();
}//GEN-LAST:event_nodeconfigokButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NodeConfig dialog = new NodeConfig(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox addressingtypeComboBox;
    private javax.swing.JLabel addressingtypeLabel;
    private javax.swing.JComboBox adhocComboBox;
    private javax.swing.JLabel adhocLabel;
    private javax.swing.JRadioButton agentRadioButton;
    private javax.swing.JRadioButton agentRadioButton1;
    private javax.swing.JLabel agenttraceLabel;
    private javax.swing.ButtonGroup agenttracebuttonGroup;
    private javax.swing.JComboBox antennatypeComboBox;
    private javax.swing.JLabel antennatypeLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox channeltypeComboBox;
    private javax.swing.JLabel channeltypeLabel;
    private javax.swing.JComboBox energymodeComboBox;
    private javax.swing.JFormattedTextField idlepowerFormattedTextField;
    private javax.swing.JFormattedTextField ifqlengthFormattedTextField;
    private javax.swing.JLabel ifqlengthLabel;
    private javax.swing.JComboBox ifqtypeComboBox;
    private javax.swing.JLabel ifqtypeLabel;
    private javax.swing.JFormattedTextField initialenergyFormattedTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox lltypeComboBox;
    private javax.swing.JLabel lltypeLabel;
    private javax.swing.JLabel mactraceLabel;
    private javax.swing.JRadioButton mactraceRadioButton;
    private javax.swing.JRadioButton mactraceRadioButton1;
    private javax.swing.ButtonGroup mactracebuttonGroup;
    private javax.swing.JComboBox mactypeComboBox;
    private javax.swing.JLabel mactypeLabel;
    private javax.swing.JRadioButton mobileipRadioButton1;
    private javax.swing.JRadioButton mobileipRadioButton2;
    private javax.swing.ButtonGroup mobileipRadioButtonGroup;
    private javax.swing.JRadioButton movtraceRadioButton;
    private javax.swing.JRadioButton movtraceRadioButton1;
    private javax.swing.ButtonGroup movtracebuttonGroup;
    private javax.swing.JButton nodeconfigokButton;
    private javax.swing.JButton nodeconfigresetButton;
    private javax.swing.JComboBox phytypeComboBox;
    private javax.swing.JLabel phytypeLabel;
    private javax.swing.JComboBox proptypeComboBox;
    private javax.swing.JLabel proptypeLabel;
    private javax.swing.JRadioButton routerRadioButton;
    private javax.swing.JRadioButton routerRadioButton1;
    private javax.swing.ButtonGroup routertracebuttonGroup;
    private javax.swing.JFormattedTextField rxpowerFormattedTextField;
    private javax.swing.JLabel topoLabel;
    private javax.swing.JFormattedTextField txpowerFormattedTextField;
    private javax.swing.JRadioButton wiredroutingRadioButton;
    private javax.swing.JRadioButton wiredroutingRadioButton1;
    private javax.swing.ButtonGroup wiredroutingbuttonGroup;
    // End of variables declaration//GEN-END:variables
}
