/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewProtocol.java
 *
 * Created on Jan 12, 2011, 1:13:24 AM
 */
package flexisim.routing.protocols;

import flexisim.views.FlexiSimView;
import flexisim.views.NewProject;
import java.io.File;

/**
 *
 * @author harshit
 */
public class NewProtocol extends javax.swing.JDialog {

    /** Creates new form NewProtocol */
    public NewProtocol(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameProtocolLabel = new javax.swing.JLabel();
        protocolNameTextField = new javax.swing.JTextField();
        protocolOkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(flexisim.views.FlexiSimApp.class).getContext().getResourceMap(NewProtocol.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        nameProtocolLabel.setText(resourceMap.getString("nameProtocolLabel.text")); // NOI18N
        nameProtocolLabel.setName("nameProtocolLabel"); // NOI18N

        protocolNameTextField.setText(resourceMap.getString("protocolNameTextField.text")); // NOI18N
        protocolNameTextField.setName("protocolNameTextField"); // NOI18N

        protocolOkButton.setText(resourceMap.getString("protocolOkButton.text")); // NOI18N
        protocolOkButton.setName("protocolOkButton"); // NOI18N
        protocolOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protocolOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameProtocolLabel)
                .addGap(18, 18, 18)
                .addComponent(protocolNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(protocolOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameProtocolLabel)
                    .addComponent(protocolNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(protocolOkButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void protocolOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protocolOkButtonActionPerformed

        File f = new File(NewProject.obpd.getFile().getParent() + "//" + protocolNameTextField.getText());
        try {
            if (f.mkdir()) {
                NewProject.obprd = new NewProtocolData();
                NewProject.obprd.setProtocolName(protocolNameTextField.getText());
                FlexiSimView.statusTextArea.append("Protocol created successfully\n");
                NewProject.obprd.setProtocolFile(new File(f.getPath() + "//" + protocolNameTextField.getText()));
                NewProject.obpd.setLog("Protocol created successfully\n");
                NewProject.obpd.setProtocol(true);
                FlexiSimView.tabCreater(protocolNameTextField.getText() + ".cc");
                NewProject.obpd.setModifyprotocoltab(false, NewProject.obpd.getI());
            } else {
                FlexiSimView.statusTextArea.append("Protocol not created\n");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        dispose();
    }//GEN-LAST:event_protocolOkButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NewProtocol dialog = new NewProtocol(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nameProtocolLabel;
    private javax.swing.JTextField protocolNameTextField;
    private javax.swing.JButton protocolOkButton;
    // End of variables declaration//GEN-END:variables
}
