/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewLink.java
 *
 * Created on Sep 18, 2010, 4:15:50 AM
 */
package flexisim.link;

import java.text.NumberFormat;
import flexisim.views.FlexiSimView;
import flexisim.views.NewProject;
import flexisim.node.NewNode;
import flexisim.views.FlexiSimApp;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author harshit
 */
public class NewLink extends javax.swing.JDialog {

    public String linkType, n1, n2, bdunit, dunit, overflow;
    int i = 0;
    Number bdvalue;
    long dvalue;
    boolean flag = true;

    /** Creates new form NewLink */
    public NewLink(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linkTypeLabel = new javax.swing.JLabel();
        linkTypeComboBox = new javax.swing.JComboBox();
        node1LinkLabel = new javax.swing.JLabel();
        node1LinkComboBox = new javax.swing.JComboBox();
        node2LinkLabel = new javax.swing.JLabel();
        node2LinkComboBox = new javax.swing.JComboBox();
        bandwidthLabel = new javax.swing.JLabel();
        bandwidthComboBox = new javax.swing.JComboBox();
        delayLabel = new javax.swing.JLabel();
        delayComboBox = new javax.swing.JComboBox();
        overflowLabel = new javax.swing.JLabel();
        overflowComboBox = new javax.swing.JComboBox();
        okLinkButton = new javax.swing.JButton();
        bandwidthFormattedTextField = new javax.swing.JFormattedTextField(new DecimalFormat("#.00"));
        delayFormattedTextField = new javax.swing.JFormattedTextField(NumberFormat.getIntegerInstance());
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(flexisim.views.FlexiSimApp.class).getContext().getResourceMap(NewLink.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        linkTypeLabel.setText(resourceMap.getString("linkTypeLabel.text")); // NOI18N
        linkTypeLabel.setName("linkTypeLabel"); // NOI18N

        linkTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "duplex-link","simplex-link" }));
        linkTypeComboBox.setName("linkTypeComboBox"); // NOI18N

        node1LinkLabel.setText(resourceMap.getString("node1LinkLabel.text")); // NOI18N
        node1LinkLabel.setName("node1LinkLabel"); // NOI18N

        node1LinkComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        for(int i=0;i<50;i++)
        {
            if(NewProject.obnm.getNodename(i)!=null)
            node1LinkComboBox.addItem(NewProject.obnm.getNodename(i));
        }
        node1LinkComboBox.setToolTipText("Select the Node");
        node1LinkComboBox.setName("node1LinkComboBox"); // NOI18N

        node2LinkLabel.setText(resourceMap.getString("node2LinkLabel.text")); // NOI18N
        node2LinkLabel.setName("node2LinkLabel"); // NOI18N

        node2LinkComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        for(int i=0;i<50;i++)
        {
            if(NewProject.obnm.getNodename(i)!=null)
            node2LinkComboBox.addItem(NewProject.obnm.getNodename(i));
        }
        node2LinkComboBox.setName("node2LinkComboBox");

        bandwidthLabel.setText(resourceMap.getString("bandwidthLabel.text")); // NOI18N
        bandwidthLabel.setName("bandwidthLabel"); // NOI18N

        bandwidthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kb", "Mb", "Gb"}));
        bandwidthComboBox.setName("bandwidthComboBox"); // NOI18N

        delayLabel.setText(resourceMap.getString("delayLabel.text")); // NOI18N
        delayLabel.setName("delayLabel"); // NOI18N

        delayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ms", "s","us"}));
        delayComboBox.setName("delayComboBox"); // NOI18N

        overflowLabel.setText(resourceMap.getString("overflowLabel.text")); // NOI18N
        overflowLabel.setName("overflowLabel"); // NOI18N

        overflowComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DropTail", "SFQ", "FQ", "DRR","RED","CBQ" }));
        overflowComboBox.setName("overflowComboBox"); // NOI18N

        okLinkButton.setText(resourceMap.getString("okLinkButton.text")); // NOI18N
        okLinkButton.setName("okLinkButton"); // NOI18N
        getRootPane().setDefaultButton (okLinkButton);
        okLinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okLinkButtonActionPerformed(evt);
            }
        });

        bandwidthFormattedTextField.setText(resourceMap.getString("bandwidthFormattedTextField.text")); // NOI18N
        bandwidthFormattedTextField.setName("bandwidthFormattedTextField"); // NOI18N

        delayFormattedTextField.setText(resourceMap.getString("delayFormattedTextField.text")); // NOI18N
        delayFormattedTextField.setName("delayFormattedTextField"); // NOI18N

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(linkTypeLabel)
                            .addComponent(node1LinkLabel)
                            .addComponent(node2LinkLabel)
                            .addComponent(bandwidthLabel)
                            .addComponent(delayLabel)
                            .addComponent(overflowLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(delayFormattedTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bandwidthFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bandwidthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(delayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(163, 163, 163))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(overflowComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(node2LinkComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(node1LinkComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(linkTypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 232, Short.MAX_VALUE))
                                .addContainerGap(74, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okLinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkTypeLabel)
                    .addComponent(linkTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(node1LinkLabel)
                    .addComponent(node1LinkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(node2LinkLabel)
                    .addComponent(node2LinkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bandwidthLabel)
                    .addComponent(bandwidthFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bandwidthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delayLabel)
                    .addComponent(delayFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(overflowComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overflowLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton)
                    .addComponent(okLinkButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okLinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okLinkButtonActionPerformed
        // TODO add your handling code here

        linkType = (String) linkTypeComboBox.getSelectedItem();
        n1 = (String) node1LinkComboBox.getSelectedItem();
        n2 = (String) node2LinkComboBox.getSelectedItem();
        try {
            bdvalue = (Number) bandwidthFormattedTextField.getValue();
        } catch (NullPointerException ne) {
            dispose();
            JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
            JOptionPane.showMessageDialog(mainFrame, "Bandwidth must be specified.", "Link Cannot be Created", JOptionPane.ERROR_MESSAGE);
            flag = false;
        }
        bdunit = (String) bandwidthComboBox.getSelectedItem();
        try {
            dvalue = (Long) delayFormattedTextField.getValue();
        } catch (NullPointerException ne) {
            dispose();
            JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
            JOptionPane.showMessageDialog(mainFrame, "Delay must be specified.", "Link Cannot be Created", JOptionPane.ERROR_MESSAGE);
            flag = false;
        }
        dunit = (String) delayComboBox.getSelectedItem();
        overflow = (String) overflowComboBox.getSelectedItem();
        if (flag == true) {
            if (n1.equals(n2)) {
                dispose();
                JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
                JOptionPane.showMessageDialog(mainFrame, "Different nodes should be selected.", "Link Cannot be Created", JOptionPane.ERROR_MESSAGE);

            } else if (NewProject.oblm.checkRepeat(n1, n2) == 1) {
                dispose();
                JFrame mainFrame = FlexiSimApp.getApplication().getMainFrame();
                JOptionPane.showMessageDialog(mainFrame, "Link already exists between the selected nodes.", "Link Cannot be Created", JOptionPane.ERROR_MESSAGE);

            } else {
                FlexiSimView.statusTabbedPane.setSelectedIndex(0);
                FlexiSimView.statusTextArea.append("Link between " + n1 + " and " + n2 + " of " + linkType + " with bandwidth " + bdvalue + bdunit + ", delay " + dvalue + dunit + " and overflow mechanism is " + overflow + "\n");
                NewProject.obpd.setLog("Link between " + n1 + " and " + n2 + " of " + linkType + " with bandwidth " + bdvalue + bdunit + ", delay " + dvalue + dunit + " and overflow mechanism is " + overflow + "\n");
                NewProject.oblm.addLink(n1, n2);
                NewNode.obj.linkWrite(linkType, n1, n2, bdvalue.doubleValue(), bdunit, dvalue, dunit, overflow);
                FlexiSimView.codeTextAreaWrite();
                dispose();
            }
        }
    }//GEN-LAST:event_okLinkButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NewLink dialog = new NewLink(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bandwidthComboBox;
    private javax.swing.JFormattedTextField bandwidthFormattedTextField;
    private javax.swing.JLabel bandwidthLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox delayComboBox;
    private javax.swing.JFormattedTextField delayFormattedTextField;
    private javax.swing.JLabel delayLabel;
    private javax.swing.JComboBox linkTypeComboBox;
    private javax.swing.JLabel linkTypeLabel;
    private javax.swing.JComboBox node1LinkComboBox;
    private javax.swing.JLabel node1LinkLabel;
    private javax.swing.JComboBox node2LinkComboBox;
    private javax.swing.JLabel node2LinkLabel;
    private javax.swing.JButton okLinkButton;
    private javax.swing.JComboBox overflowComboBox;
    private javax.swing.JLabel overflowLabel;
    // End of variables declaration//GEN-END:variables
}
